SISPROV6/infra-code-libs

.github/workflows/main.yml, .github/workflows/only-tests.yml, projects/ngx-sp-infra/package.json, projects/ngx-sp-infra/src/lib/widgets/lib-combobox/lib-combobox.component.html, projects/ngx-sp-infra/src/lib/widgets/lib-combobox/lib-combobox.component.spec.ts, projects/ngx-sp-infra/src/lib/widgets/lib-combobox/lib-combobox.component.ts
Este commit contém duas coisas:
1. Ajuste citado na task do Azure: https://dev.azure.com/SisproERP/PeD/_workitems/edit/35
2. Primeiro teste de proteção de branches com PRs e sucesso de Actions.
=> R-58852/35

projects/ngx-sp-infra/package.json, projects/ngx-sp-infra/src/lib/utils/utils.ts
Contém:
1. Ajuste citado na task do Azure: https://dev.azure.com/SisproERP/PeD/_workitems/edit/38
=> R-58852/38

projects/ngx-sp-infra/package.json
=> ngx-sp-infra | v4.0.19 | Commit automático

projects/ngx-sp-infra/package.json, projects/ngx-sp-infra/src/lib/widgets/table/table.component.html, projects/ngx-sp-infra/src/lib/widgets/table/table.component.scss
Ajuste da largura da coluna de checkbox
=> ngx-sp-infra | v4.0.20 | Commit automático

CONTRIBUTING.md, RELEASE_GUIDE.md, deploy/index.js, projects/ngx-sp-auth/README.md, projects/ngx-sp-infra/README.md
Ajuste das documentações e scripts
=> Docs e scripts

projects/ngx-sp-infra/src/lib/infra.module.ts, projects/ngx-sp-infra/src/lib/widgets/auditoria-button/auditoria-button.component.html, projects/ngx-sp-infra/src/lib/widgets/auditoria-button/auditoria-button.component.ts, projects/ngx-sp-infra/src/lib/widgets/lib-header/lib-header.component.ts, projects/ngx-sp-infra/src/public-api.ts
adicionando mudanças no botão de auditoria e criando o componente isolado
=> adicionando mudanças no botao de auditoria e craindo o componente isolado

projects/ngx-sp-infra/package.json
ngx-sp-infra | v4.3.2 | Commit automático
=> ngx-sp-infra | v4.3.2 | Commit automático

projects/ngx-sp-infra/package.json
=> ngx-sp-infra | v5.7.4 | Commit automático

projects/ngx-sp-infra/package.json, projects/ngx-sp-infra/src/lib/models/table/header-structure.model.ts, projects/ngx-sp-infra/src/lib/widgets/lib-simplified-table/lib-simplified-table.component.html
Modificada lógica para exibir tooltip customizado na table-simplificada
=> ngx-sp-infra | v5.7.6 | Commit automático

projects/ngx-sp-auth/src/public-api.ts
=> Ajustes apis públicas

deploy/release-info.json, projects/ngx-sp-auth/package-lock.json, projects/ngx-sp-auth/package.json
Liberação de versão estável com implementações das últimas duas semanas
=> ngx-sp-auth | v4.0.0 | Commit automático

deploy/release-info.json, projects/ngx-sp-auth/package-lock.json, projects/ngx-sp-auth/package.json
Implementação do Controle de Versões do Corporativo e Infra
=> ngx-sp-auth | v4.0.2 | Commit automático

deploy/release-info.json, projects/ngx-sp-auth/package-lock.json, projects/ngx-sp-auth/package.json
Liberação semanal - contém as liberações e correções dos componentes desde a quinta-feira passada (25/09)
=> ngx-sp-auth | v4.0.3 | Commit automático

deploy/release-info.json, projects/ngx-sp-infra/package.json
Liberação de teste para validar novo projeto de telas
=> ngx-sp-infra | v6.0.4 | Commit automático

deploy/release-info.json, projects/ngx-sp-auth/package-lock.json, projects/ngx-sp-auth/package.json
Liberação de teste para validar novo projeto de telas
=> ngx-sp-auth | v4.0.4 | Commit automático

deploy/release-info.json, projects/ngx-sp-views/package-lock.json, projects/ngx-sp-views/package.json, projects/ngx-sp-views/src/lib/custom/lib-custom-configerp-environment.service.ts, projects/ngx-sp-views/src/lib/custom/models/icustom-configerp-environment-service.ts, projects/ngx-sp-views/src/lib/custom/token.ts, projects/ngx-sp-views/src/lib/services/configuracao-senha.service.ts, projects/ngx-sp-views/src/lib/services/queue.service.ts, projects/ngx-sp-views/src/lib/views/lib-authentication-config/services/infra-authentication.service.ts, projects/ngx-sp-views/src/lib/views/lib-integracao-ldap/services/integracao-ad-ldap.service.ts, projects/ngx-sp-views/src/lib/views/lib-integracoes-externas/services/cadastro-integracoes-externas.service.ts, projects/ngx-sp-views/src/lib/views/logs-api/services/logs-api.service.ts, projects/ngx-sp-views/src/lib/views/logs-data-access/services/logs-data-access.service.ts, projects/ngx-sp-views/src/lib/views/logs-email/services/logs-email.service.ts, projects/ngx-sp-views/src/lib/views/logs-geral/services/logs-geral.service.ts, projects/ngx-sp-views/src/lib/views/logs-report/services/logs-report.service.ts, projects/ngx-sp-views/src/lib/views/logs-timer/services/logs-timer.service.ts, projects/ngx-sp-views/src/lib/views/logs-ws/services/logs-ws.service.ts, projects/ngx-sp-views/src/public-api.ts
Liberação de ajuste dos services, foi feita uma implementação semelhante ao Auth
=> ngx-sp-views | v1.0.1 | Commit automático

deploy/release-info.json, projects/ngx-sp-infra/package.json, projects/ngx-sp-infra/src/lib/widgets/lib-combobox-rework/lib-combobox-rework.component.ts, projects/ngx-sp-infra/src/lib/widgets/table/table.component.ts
Emissão de novo evento de mudança de sorting na lib-table
=> ngx-sp-infra | v6.0.6 | Commit automático

deploy/release-info.json, projects/components-showcase/src/app/app.component.html, projects/components-showcase/src/app/app.component.ts, projects/ngx-sp-infra/package.json, projects/ngx-sp-infra/src/lib/widgets/lib-combobox-rework/lib-combobox-rework.component.ts
Seleção de valores integrada com formulários no componente lib-combobox-rework agora retorna o ID e o evento (selectionChange) retorna o objeto completo.
=> ngx-sp-infra | v6.0.8 | Commit automático

deploy/release-info.json, projects/ngx-sp-auth/package-lock.json, projects/ngx-sp-auth/package.json
Liberação da versão @latest semanal com todas implementações e correções incluídas da @next
=> ngx-sp-auth | v4.1.0 | Commit automático

deploy/release-info.json, projects/ngx-sp-auth/package-lock.json, projects/ngx-sp-views/package-lock.json, projects/ngx-sp-views/package.json
Liberação da versão @latest semanal com todas implementações e correções incluídas da @next
=> ngx-sp-views | v2.1.0 | Commit automático
